FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /build

COPY ["nuget.config", "./"]

COPY ["DMSG3.Domain/DMSG3.Domain.csproj", "DMSG3.Domain/"]
COPY ["DMSG3.Infrastructure/DMSG3.Infrastructure.csproj", "DMSG3.Infrastructure/"]
COPY ["DMSG3.REST/DMSG3.REST.csproj", "DMSG3.REST/"]

ENV NUGET_PACKAGES=/root/.nuget/packages
RUN mkdir -p /root/.nuget/packages

RUN dotnet restore "DMSG3.REST/DMSG3.REST.csproj"

COPY . .

WORKDIR /build/DMSG3.REST
RUN dotnet publish "DMSG3.REST.csproj" -c Release -o /out --no-restore

FROM base AS final
WORKDIR /app
COPY --from=build /out .
ENTRYPOINT ["dotnet", "DMSG3.REST.dll"]