// <auto-generated />
using System;
using DMSG3.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DMSG3.Infrastructure.Migrations
{
    [DbContext(typeof(DMSG3_DbContext))]
    [Migration("20260201124500_AddVirusScanAnalysisId")]
    partial class AddVirusScanAnalysisId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DMSG3.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("OcrCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocr_completed_at");

                    b.Property<string>("OcrError")
                        .HasColumnType("text")
                        .HasColumnName("ocr_error");

                    b.Property<DateTime?>("OcrStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocr_started_at");

                    b.Property<string>("OcrStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ocr_status")
                        .HasDefaultValue("Pending");

                    b.Property<string>("OcrText")
                        .HasColumnType("text")
                        .HasColumnName("ocr_text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageBucket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_bucket");

                    b.Property<string>("StorageObjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_object_name");

                    b.Property<DateTime?>("SummaryCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("summary_completed_at");

                    b.Property<string>("SummaryError")
                        .HasColumnType("text")
                        .HasColumnName("summary_error");

                    b.Property<string>("SummaryStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary_status")
                        .HasDefaultValue("Pending");

                    b.Property<string>("SummaryText")
                        .HasColumnType("text")
                        .HasColumnName("summary_text");

                    b.Property<DateTime>("UploadTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VirusScanAnalysisId")
                        .HasColumnType("text")
                        .HasColumnName("virus_scan_analysis_id");

                    b.Property<DateTime?>("VirusScanCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("virus_scan_completed_at");

                    b.Property<string>("VirusScanError")
                        .HasColumnType("text")
                        .HasColumnName("virus_scan_error");

                    b.Property<DateTime?>("VirusScanStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("virus_scan_started_at");

                    b.Property<string>("VirusScanStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("virus_scan_status")
                        .HasDefaultValue("NotScanned");

                    b.HasKey("Id");

                    b.HasIndex("UploadTime")
                        .HasDatabaseName("ix_documents_upload_time");

                    b.ToTable("documents", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
